# Generated by Django 5.2.6 on 2025-09-10 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="标签"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="平均评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词",
                "verbose_name_plural": "提示词管理",
            },
        ),
        migrations.CreateModel(
            name="PromptHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="历史内容")),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("use", "使用"),
                            ("optimize", "优化"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt.prompt",
                        verbose_name="关联提示词",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词历史",
                "verbose_name_plural": "提示词历史记录",
            },
        ),
        migrations.CreateModel(
            name="PromptStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "total_usage",
                    models.IntegerField(default=0, verbose_name="总使用次数"),
                ),
                (
                    "daily_usage",
                    models.IntegerField(default=0, verbose_name="当日使用次数"),
                ),
                (
                    "weekly_usage",
                    models.IntegerField(default=0, verbose_name="本周使用次数"),
                ),
                (
                    "monthly_usage",
                    models.IntegerField(default=0, verbose_name="本月使用次数"),
                ),
                ("total_score", models.FloatField(default=0.0, verbose_name="总评分")),
                (
                    "score_count",
                    models.IntegerField(default=0, verbose_name="评分次数"),
                ),
                (
                    "optimization_count",
                    models.IntegerField(default=0, verbose_name="优化次数"),
                ),
                (
                    "average_optimization_improvement",
                    models.FloatField(default=0.0, verbose_name="平均优化提升率"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "prompt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt.prompt",
                        verbose_name="关联提示词",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词统计",
                "verbose_name_plural": "提示词统计数据",
            },
        ),
    ]
