# Generated by Django 5.2.6 on 2025-09-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstatistics",
            name="generation_count",
            field=models.IntegerField(default=0, verbose_name="生成次数"),
        ),
        migrations.AlterField(
            model_name="prompthistory",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create", "创建"),
                    ("update", "更新"),
                    ("use", "使用"),
                    ("optimize", "优化"),
                    ("generate", "生成"),
                    ("evaluate", "评估"),
                ],
                max_length=50,
                verbose_name="操作类型",
            ),
        ),
    ]
